import type { Metadata } from 'next'
import { DM_Serif_Display } from 'next/font/google'
import './globals.css'

const inter = DM_Serif_Display({subsets: ['latin'], weight: ['400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
